coverage:
  range: 75..90
  round: down
  precision: 2
ignore:
  - "main.go"
  - "scripts"
  - "internal/ddl/foreign_key_parser.go"
  - "internal/ddl/index_parser.go"
  - "internal/ddl/trigger_parser.go"
