version: 1
cli:
  server: https://app.fossa.io
  fetcher: custom
  project: pgutil
analyze:
  modules:
  - name: github.com/sjansen/pgutil
    type: go
    target: github.com/sjansen/pgutil
    path: .
    options:
      all-tags: true
