run:
    deadline: 3m
    issues-exit-code: 1
    tests: true
    build-tags:
    - integration

issues:
  exclude-rules:
  - path: _parser\.go$
    linters:
     - gocritic
     - gocyclo
     - golint

linters:
    enable:
    - deadcode
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosimple
    - govet
    - ineffassign
    - lll
    - megacheck
    - misspell
    - structcheck
    - typecheck
    - varcheck
    disable:
    - errcheck  # configurable ignore
    - maligned
    fast: false

linters-settings:
    gocyclo:
        min-complexity: 15
    golint:
        min-confidence: 0
    lll:
        tab-width: 8
    maligned:
        suggest-new: true
