exclude: '^vendor/'
repos:
-  repo: local
   hooks:
   -  id: jsonnet
      name: jsonnet
      language: system
      entry: jsonnet fmt --test
      pass_filenames: true
      files: '.*\.jsonnet$'
   -  id: vet
      name: go vet
      language: system
      entry: go vet  ./...
      pass_filenames: false
      types: [go]
   -  id: lint
      name: golangci
      language: system
      entry: golangci-lint run
      pass_filenames: false
      types: [go]
