version: '2.1'
services:
  go:
    build:
      context: ./docker/go
    command: ./scripts/run-all-tests
    environment:
      GO111MODULE: "on"
      PGHOST:     "pg"
      PGDATABASE: "pgutil"
      PGUSER:     "docker"
      PGPASSWORD: ""
    links:
     - pg
    volumes:
     - .:/go/src/github.com/sjansen/pgutil
     - "${GOPATH:-/tmp}/pkg/mod:/go/pkg/mod"
    working_dir: /go/src/github.com/sjansen/pgutil
  pg:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_DB:   "pgutil"
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: ""
    volumes:
     - ./scripts/initdb.d:/docker-entrypoint-initdb.d
